import {
  ArrowRight,
  ArrowUpRight,
  BadgeCheck,
  CalendarCheck,
  Check,
  CheckCircle2,
  ChevronDown,
  ClipboardList,
  Clock,
  ClipboardCheck,
  Droplets,
  Heart,
  Lock,
  MapPin,
  Menu,
  MessageCircleQuestion,
  Microscope,
  Navigation,
  Phone,
  PhoneCall,
  Quote,
  ShieldCheck,
  Sparkles,
  Sprout,
  Star,
  Stethoscope,
  Syringe,
  TestTubes,
  User,
  UserRound,
  Users,
  X,
} from 'lucide-react'

const ICONS = {
  ArrowRight,
  ArrowUpRight,
  BadgeCheck,
  CalendarCheck,
  Check,
  CheckCircle2,
  ChevronDown,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Droplets,
  Heart,
  Lock,
  MapPin,
  Menu,
  MessageCircleQuestion,
  Microscope,
  Navigation,
  Phone,
  PhoneCall,
  Quote,
  ShieldCheck,
  Sparkles,
  Sprout,
  Star,
  Stethoscope,
  Syringe,
  TestTubes,
  User,
  UserRound,
  Users,
  X,
}

/** Resolves a lucide icon by name so section data can stay plain JSON. */
export default function Icon({ name, size = 20, ...rest }) {
  const Glyph = ICONS[name]
  if (!Glyph) return null
  return <Glyph size={size} strokeWidth={1.6} {...rest} />
}
